# Generated by Django 5.0 on 2024-01-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="mobile",
            field=models.BigIntegerField(default=0),
        ),
    ]
