# Generated by Django 5.0 on 2024-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0002_alter_registration_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_image", models.ImageField(upload_to="uploads/category")),
                (
                    "category_name",
                    models.CharField(default="", max_length=100, null=True),
                ),
            ],
        ),
    ]
