# Generated by Django 5.0 on 2024-01-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0003_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(upload_to="uploads/category/"),
        ),
    ]
