# Generated by Django 5.0 on 2024-01-18 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0004_alter_category_category_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
