# Generated by Django 5.0 on 2024-01-18 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0006_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_image", models.ImageField(upload_to="uploads/product")),
                (
                    "product_name",
                    models.CharField(default="", max_length=100, null=True),
                ),
                ("product_price", models.IntegerField(default=1)),
                (
                    "product_desc",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flipkart.category",
                    ),
                ),
            ],
        ),
    ]
